name: Build & Deploy Lambda Image

on:
  push:
    paths:
      - 'apps/**'
permissions:
  id-token: write
  contents: read

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker image
        run: |
          IMAGE_TAG=sha-${{ github.sha }}
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}:$IMAGE_TAG apps/scraper
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}:$IMAGE_TAG
          echo "::set-output name=image_uri::${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}:$IMAGE_TAG"

      - name: Deploy Lambda via lambroll
        working-directory: apps/scraper
        run: |
          lambroll deploy --image-uri "${{ steps.build-and-push.outputs.image_uri }}"
