name: Build & Deploy Scraper

on:
  push:
    paths:
      - 'apps/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  ECR_REPO: fit-scraper

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker
        id: build-push
        run: |
          IMAGE_TAG=sha-${{ github.sha }}
          REPO_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}
          docker build -t $REPO_URI:$IMAGE_TAG apps/scraper
          docker push $REPO_URI:$IMAGE_TAG
          echo "image_uri=$REPO_URI:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Deploy Lambda via lambroll
        working-directory: apps/scraper
        run: |
          lambroll deploy --image-uri "${{ steps.build-push.outputs.image_uri }}"
